### ISSUE TITLE
[Request] Il valore di una Borraccia

### ISSUE THREAD

**Issue by GuardiaHTML** [DevLan-Support/tickets#11]
**Modifica particolare di un oggetto all'interno del Server**

- Borraccia 

**Risultato Attuale:**

- Durabilità: 30

- Sazietà/Ripristino: mezza goccia 

- Poter utilizzare la Borraccia nonostante la barra della sete sia piena

**Soluzione:**

- Durabilità: invariata (non strettamente necessario) 

- Sazietà/Ripristino: una goccia (minimo) 

- Blocco dell'utilizzo della Borraccia quando la barra della sete è piena (Nel caso, inserire un avviso riguardo l'utilizzo) 

**Allegato:**

- Nullo

**Comment by Fargus5** [comment]
Aumentata la durabilità della borraccia a 50, prima era a 30.
Aumentato il ripristino della sete a 1.5
